language: node_js
node_js:
  - "node"
before_deploy:
  - npm run build
deploy:
  provider: script
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
    - npm publish
  on:
    tags: true
    branch: master
