language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: nicolas.vanhoren@gmail.com
  api_key:
    secure: XVqNIjGMDHqrQJGxEpqVmNERskv5rfo/DvIIgU7QJB2lDi5Tw7SEilna5alqCsCyP4Cg8z4zKl4Zq4PtjCDB2V+xJ0UxjnqsrBloKZkCyq3TYEkUOkgC/krL6vP89qroxpvJdFsV7v6lA7v0v2CEZACb+S1sNGgCTxxu3zYPEZnkhlMjelvnd4oaZBDdfeGr9t/8YH2PxuUe+F0z20Fr3wgjx9Sc5f5rvrbOU9bKLR4BWUR6hjmLuLnlZYYG71asQ6wvlMEhGfXfi6HPIvcyDvR42V8t3B2L2A2CXGyVoUopRglTXS7HV63rbSFtFVWp3urNMXYRB6sX6oJVc4p6bu4TR2PJo0Vvbki4M6yG3pLEokcMByeD4g7NKGrKVRuNkj+bVYA93AnJbmZDJbX7ZFKzj6vSnSA2FUEE606Rn+frboOmXn6xah3nVFpEh3fkwykpgyRzXoxKBKVaOmiUdH08cYd+q4ApQIUbdn+Tm7D+mdEOf5X1xYrpnGGF/GA7JfLPxBJhDe0E+sAehLo1AmujrfkY0TKtRx4CHamRCe1pBH9VMgBZb/iPV6fHM8MxrHsCa0ezxwbIhVFQg6M3ily28Mo4Tu9s/KbFolLi17/uGbZy4IdptCTfy9go3pLVs9D0AHrf26YcmT8Lva6+cUu0wv60BDx1RejxSY+NuQ0=
  on:
    tags: true
    repo: nicolas-van/legado
    branch: master
